
### Среда разработки
## Конфигурация порта
server:
  port: 8080
spring:
  datasource: ## Конфигурация базы данных
    url: jdbc:h2:mem:mapstruct
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true

  jpa:
    database: h2  # Тип базы данных
    show-sql: true   # Печать оператора SQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
