### Среда разработки

## Конфигурация порта
server:
  port: 8080
spring:
  datasource: ## Конфигурация базы данных
#    В памяти
#    url: jdbc:h2:mem:mapstruct
#    В файле
    url: jdbc:h2:file:~/.h2/mapstruct;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true


  jpa:
    database: h2  # Тип базы данных
    show-sql: true   # Печать оператора SQL
    hibernate:
#      БД дополняется
#      ddl-auto: update
#      БД пересоздается с нуля
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
